apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gs6kuy0fh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gs6kuy0fh-python 
  name: gs6kuy0fh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gs6kuy0fh-python 
