apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gs6kuy0fh-python 
  janus-idp.io/tekton: gs6kuy0fh-python
  backstage.io/kubernetes-id: gs6kuy0fh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gs6kuy0fh-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml