apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gs6kuy0fh-python-gitops
  description: This is GitOps manifest for gs6kuy0fh-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gs6kuy0fh-python
    backstage.io/kubernetes-id: gs6kuy0fh-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gs6kuy0fh-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gs6kuy0fh-python
